### ISSUE TITLE
The annotation values in the format field of the vcf are not showing.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#1028]
I select the format annotation fields, which have values, but all value are blank in the VariantInspectCard.
<img width="1178" alt="Screenshot 2023-10-22 at 6 29 23 PM" src="https://github.com/iobio/gene.iobio/assets/8420103/76c5818a-11a7-4020-8152-2c182dd1533c">
<img width="384" alt="Screenshot 2023-10-22 at 6 31 11 PM" src="https://github.com/iobio/gene.iobio/assets/8420103/14d03d25-0a25-4001-9683-16bc1e1b88ae">

**Comment by tonydisera** [comment]
@YangQi007, can you look at this as soon as possible? I'd like to have a fix before we release.  Thanks! Tony

**Comment by YangQi007** [comment]
Hi, @tonydisera I noticed that you added some code in getting formatValues, I am confused about this line of code, cause if this line of code is added, we cannot get the formatValues.
<img width="547" alt="Screenshot 2023-10-22 at 8 27 53 PM" src="https://github.com/iobio/gene.iobio/assets/60582494/add4a265-5c55-4474-af71-34eb466a8255">
