### ISSUE TITLE
The mosaic annotations are not updated to reflect the annotations of the selected variant

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#1036]
If I click on a variant in the left panel, the Mosaic annotations are correct. But then if I click on another variant, the Mosaic annotations are not refreshed and show the annotations for the previously selected variant. Also, clicking on a variant symbol (circle, square, etc.)  in the Variants card does not appear to update the Mosaic annotations.

**Comment by tonydisera** [comment]
We’ve run into a limitation with iframes as it cannot share the session from the parent frame. I had forgotten about this. So it will take some work to interact with Mosaic from gene.iobio running in clin.iobio.

**Comment by AlistairNWard** [comment]
I wouldn't worry about getting clin.iobio to work.
