### ISSUE TITLE
Error if genes added with ClinVar panel open

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#1047]
Load the demo data then click to show the ClinVar track. Now add a new gene and the following error occurs:

![Screenshot 2024-02-19 at 09 19 17](https://github.com/iobio/gene.iobio/assets/523111/b64cc1f2-ae5f-49bd-9c46-ec628cedfdad)

The variants appear to show in the ClinVar track however. If the ClinVar track is closed, you go to the gene, then open the ClinVar track, things seem to be ok.

**Comment by tonydisera** [comment]
This bug fix was multi-pronged.
1. The main problem was the options argument sent into CohortModel.loadData. This was incorrectly used in CohortModel.loadVariants() as the options argument for the call to SampleModel.promiseAnnotateVariants. 
2. There was a typo in GeneHome for the data attribute showKnownVariantsViz
3. Most importantly, there was old code that used a previous data attribute name in globalApp (GNOMAD_METHOD_BCFTOOLS was renamed to GNOMAD_METHOD_MERGE_ANNOTS.
  - And VariantInspectCard had a misspelling (GNOMAD_METHOD_MERGE**_D_**_ANNOTS)
