### ISSUE TITLE
Variant filter has a bug

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#1052]
Demo data > there is a variant in the high / moderate impact category

![Screenshot 2024-02-26 at 08 25 35](https://github.com/iobio/gene.iobio/assets/523111/cec80235-8311-435f-8f0f-553ca8a7c3cf)

Edit the filter and remove the popmax filter

![Screenshot 2024-02-26 at 08 26 17](https://github.com/iobio/gene.iobio/assets/523111/2f36ef7a-0240-4f8a-8014-b20ad05e1540)

Click apply and now there are no variants in this category. Removing the popmax filter should allow more variants in, but it seems to remove variants

![Screenshot 2024-02-26 at 08 26 50](https://github.com/iobio/gene.iobio/assets/523111/d239ef71-2756-4408-b1ed-023ce750cbea)

**Comment by tonydisera** [comment]
Yep, this is a bug. When the field is blank, no filter should be applied. I suspect it is treating the blank field as '0'. I will fix this in 4.10, which should be released and deployed this week.
