### ISSUE TITLE
Unhandled exceptions due to incorrect name in error handling

### ISSUE THREAD

**Issue by anderspitman** [iobio/gene.iobio#1069]
While working on the fibridge replacement I came across some places where `vcfUrl` is used when it should be `vcfURL`. Here's an example:

https://github.com/iobio/gene.iobio/blob/04c078e95fdf51c261cf9a2503fcb3f019f6a0e8/client/app/models/Vcf.iobio.js#L672

That causes an unhandled exception when that error condition is hit.

I could probably fix this as part of my work but just wanted to get an issue opened to make sure I don't forget about it

**Comment by tonydisera** [comment]
Thanks for spotting this @anderspitman. This fix will be in gene.iobio 4.11.
