### ISSUE TITLE
Add validation when gene.iobio is launched from Mosaic, so that the user is given an informative error message.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#1095]
gene.iobio is missing critical file validation, resulting in an error in downstream processing when variants are annotated with vcfanno, leading to a verbose and technical error message. (See error message below) 

For example, the GRCh38 WES demo project on Utah Mosaic has 2 different vcf files specified for the project. When launching gene.iobio from Mosaic for this project, the app was incorrectly assuming only on vcf file exists on the project. 

There are a number of scenarios where the user should be informed that the data files specified are either incomplete or invalid.
1. Multiple vcf or bam/cram files are specified for a sample.
2. A required file (either a vcf or a bam/cram) is missing for a sample.
3. Invalid combination of files for a trio. One of the samples loads alignments only, but other samples load variant files.
4. The vcf sample name (specified in the Mosaic sample) is missing/blank.
5. An index file isn't specified for a vcf or bam/cram, or the index file specified belongs to a different file.

`Could not annotate variants due to server error. Error: ============================================= vcfanno version 0.3.5 [built with go1.19.3] see: https://github.com/brentp/vcfanno ============================================= vcfanno.go:116: found 43 sources from 3 files normalize v0.5 options: input VCF file - [o] output VCF file - [w] sorting window size 10000 [m] no fail on masked reference inconsistency false [n] no fail on reference inconsistency true [q] quiet false [d] debug false [r] reference FASTA file /gru_data/data/references/homo_sapiens/hg38/chr1.fa decompose v0.5 options: input VCF file - [s] smart decomposition true (experimental) [o] output VCF file - subset v0.5 Options: input VCF File - [s] sample file list 1 samples [E::bgzf_read_block] Invalid BGZF header at offset 490442 Reading "https://mosaic.chpc.utah.edu/api/v1/files/serve/65c0fbb5-1826-47c6-a47e-b92e5249d1f7.vcf.gz##idx##https://mosaic.chpc.utah.edu/api/v1/files/serve/2d4cfd95-ab21-4261-aed5-a34acbffe8e3.vcf.gz.tbi" failed stats: samples : 1/3 variants : 0/0 Time elapsed: 0.01s stats: no. variants : 0 no. biallelic variants : 0 no. multiallelic variants : 0 no. additional biallelics : 0 total no. of biallelics : 0 Time elapsed: 0.01s Unknown option: no_plugins Ignoring unsupported option 'no_plugins' found via ENV variable or INI file Unknown option: no_htslib Ignoring unsupported option 'no_htslib' found via ENV variable or INI file Unknown option: pluginsdir Ignoring unsupported option 'pluginsdir' found via ENV variable or INI file Unknown option: no_update Ignoring unsupported option 'no_update' found via ENV variable or INI file stats: biallelic no. left trimmed : 0 no. right trimmed : 0 no. left and right trimmed : 0 no. right trimmed and left aligned : 0 no. left aligned : 0 total no. biallelic normalized : 0 multiallelic no. left trimmed : 0 no. right trimmed : 0 no. left and right trimmed : 0 no. right trimmed and left aligned : 0 no. left aligned : 0 total no. multiallelic normalized : 0 total no. variants normalized : 0 total no. variants observed : 0 total no. reference observed : 0 Time elapsed: 0.01s vcfanno.go:157: falling back to non-bgzip api.go:811: WARNING: using op 'self' when with Number='1' for 'ALLELEID' from '/iobio-gru-backend/static/clinvar/GRCh38/clinvar.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'ID' from '/iobio-gru-backend/static/clinvar/GRCh38/clinvar.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'AN' from '/gru_data/annotations/GRCh38/gnomad/gnomad.genomes.v4.0.0.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'AF_popmax' from '/gru_data/annotations/GRCh38/gnomad/gnomad.genomes.v4.0.0.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'nonpar' from '/gru_data/annotations/GRCh38/gnomad/gnomad.genomes.v4.0.0.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'VarDP' from '/gru_data/annotations/GRCh38/gnomad/gnomad.genomes.v4.0.0.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'AN' from '/gru_data/annotations/GRCh38/gnomad/gnomad.exomes.v4.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'AF_popmax' from '/gru_data/annotations/GRCh38/gnomad/gnomad.exomes.v4.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'nonpar' from '/gru_data/annotations/GRCh38/gnomad/gnomad.exomes.v4.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'VarDP' from '/gru_data/annotations/GRCh38/gnomad/gnomad.exomes.v4.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. api.go:811: WARNING: using op 'self' when with Number='1' for 'AF_ami' from '/gru_data/annotations/GRCh38/gnomad/gnomad.exomes.v4.calypso.vcf.gz' can result in out-of-order values when the query is multi-allelic api.go:812: : this is not an issue if the query has been decomposed. vcfanno.go:250: annotated 0 variants in 0.00 seconds (0.0 / second)`

**Comment by AlistairNWard** [comment]
Is there a valid index file for the vcf?

**Comment by tonydisera** [comment]
Strange. I cannot reproduce the error now. Yes, there does appear to be an index file. There are 2 vcf files in the project. I wonder if randomly, the other vcf is being chosen in gene.iobio.

**Comment by tonydisera** [comment]
Yep. There are 2 vcf files associated with NA12878:

<img width="1641" alt="Screenshot 2024-08-15 at 4 13 45 PM" src="https://github.com/user-attachments/assets/60d18f38-a651-4643-b059-07267cf5c3ad">

@AlistairNWard , should gene.iobio fail when this happens or pick the first vcf and warn the user about the other vcf?

**Comment by AlistairNWard** [comment]
I can't remember where we fell with this. My recollection that a vcf is picked at random and we definitely shouldn't be doing that. In my opinion, we should error out with an informative warning. The way around it for now is to associate files with an experiment and then get the vcf from the experiment. Ultimately, we could associate multiple vcf files with an experiment which would then result in the same problem. Does gene.iobio know there are multiple vcfs to pick from?

**Comment by tonydisera** [comment]
I've also added validation logic to make sure that if a trio is specified, and a sample specifies an alignment file only, the other samples must do the same.  Here is the error message:
<img width="327" alt="Screenshot 2024-08-16 at 12 19 01 PM" src="https://github.com/user-attachments/assets/5746f06a-352c-42ba-a372-492fe936c7e4">

**Comment by tonydisera** [comment]
And if a mandatory file is missing, the following alert will be issued. In this example, the user launched with an experiment, specifying alignment files for the proband and the father, but not for the mother:

<img width="325" alt="Screenshot 2024-08-16 at 12 34 06 PM" src="https://github.com/user-attachments/assets/1f0cb506-5597-4e2f-99b9-89adf497df3f">
