### ISSUE TITLE
Can't annotate MT variants

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#1106]
Put in MT-ND4 and you can select the gene, but then the following error occurs:

<img width="284" alt="Screenshot 2024-09-16 at 18 50 59" src="https://github.com/user-attachments/assets/65f4f74b-1d86-4bb8-b20f-89cd002834eb">

Sometimes the reference name is chrM, chrMT, M, or MT. Can we get the format from the header?

**Comment by tonydisera** [comment]
See related issue #1108

**Comment by tonydisera** [comment]
@AlistairNWard I looked at the gene.iobio code and it is using the ref name from the contig header rec in the vcf (when present). I am trying to find a Utah Mosaic vcf that has includes variants in chrM/chrMT/M/MT, but I wonder if it is part of the UGP pipeline to align and call mitochondrial genes or if it is part of normal library prep to include mitochondrial DNA.

**Comment by AlistairNWard** [comment]
It is standard to call MT variants, but how accurate these calls are, I'm not sure. Since the MT is haploid and the depth should be very large, there could be some idiosyncracies. Still, all UCGD vcf files have chrM variants in them
