### ISSUE TITLE
Fibridge Proxy Down

### ISSUE THREAD

**Issue by aaron-chapman** [iobio/gene.iobio#1112]
Are you guys aware, your proxy server is offline, therefore it won't load any VCFs/TBIs?

![Capture1](https://github.com/user-attachments/assets/0aaf3be2-78a8-4aaa-84c7-cf16c26428e9)
![Capture2](https://github.com/user-attachments/assets/bf2b8d0e-10b9-4483-b661-1a2fa5df1fee)

**Comment by tonydisera** [comment]
Hi Aaron –

Thank you for letting us know. I’ll try to get Fibridge restarted this evening. If I run into a snag, I will be in contact with our team member that created and supports Fibridge. He will be back in town on Monday.

Best regards,
Tony Di Sera

From: Aaron Chapman ***@***.***>
Date: Saturday, October 12, 2024 at 3:53 PM
To: iobio/gene.iobio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [iobio/gene.iobio] Fibridge Proxy Down (Issue #1112)

Are you guys aware, your proxy server is offline, therefore it won't load any VCFs/TBIs?

Capture1.png (view on web)<https://github.com/user-attachments/assets/0aaf3be2-78a8-4aaa-84c7-cf16c26428e9>
Capture2.png (view on web)<https://github.com/user-attachments/assets/bf2b8d0e-10b9-4483-b661-1a2fa5df1fee>

**Comment by tonydisera** [comment]
Hi Aaron -
Thank you for alerting us to the problem. I am trying to renew the certificate. I will keep you posted and hopefully have this resolved in the next hour. I apologize for the delay. 

Best,
Tony Di Sera

**Comment by tonydisera** [comment]
Hi Aaron @aaron-chapman -

The certificate for the fibridge is renewed. In gene.iobio, the local file processing is now functioning properly, so you should be able to load your local files without error now.

Thanks @anderspitman for your easy-to-follow directory structure and shell scripts and @stefinfection for helping me ssh to our AWS instance and renew the cert.

Thanks for your patience!
Tony Di Sera

**Comment by aaron-chapman** [comment]
Requesting this ticket to be reopened as local file processing does not work. Server appears to be offline again (as of 2024-11-7).

**Comment by anderspitman** [comment]
@aaron-chapman I don't see any recent outages, and it's working for me. Can you give more details about what you're seeing?

**Comment by aaron-chapman** [comment]
Yeah no problem, screenshots attached.
![snip1](https://github.com/user-attachments/assets/0b6d530f-82b2-4fb1-868c-73aa9e2b5843)
![snip2](https://github.com/user-attachments/assets/98150e0e-e2dd-4533-a3e7-664c8faa87d8)

**Comment by aaron-chapman** [comment]
@anderspitman If it was affected by a power outage or other issue (even if it was only for an extremely limited time), could it possibly affect some form of 'intermediate' cache? Do you guys implement server-level caching of web responses, or are all requests/responses tagged "nocache"?

**Comment by anderspitman** [comment]
That server will never respond to a ping. The simplest way to test is to navigate to https://lf-proxy.iobio.io/ with your browser, or use curl

**Comment by anderspitman** [comment]
Oh and to answer your caching question, fibridge requests should never use caches. If you see any that are that's a bug.

**Comment by aaron-chapman** [comment]
Well that's not good.. And although it was never the intention, I'm glad I
could help expose a bug for you. I will attempt this again later today when
I'm back home, without the brackets.

**Comment by anderspitman** [comment]
Actually the more I think about it caching shouldn't be a problem, since fibridge generates a new URL for every session.

**Comment by aaron-chapman** [comment]
@anderspitman It appears I can break your file handling even without the brackets...

![snip3](https://github.com/user-attachments/assets/916d0fef-c490-4cdf-81d4-4261c1c877dc)

**Comment by anderspitman** [comment]
Can you try it without the spaces too?
