### ISSUE TITLE
data source for phylop conservation scores

### ISSUE THREAD

**Issue by danielprosser1** [iobio/gene.iobio#1116]
Sorry if this isn't exactly an 'issue' but I'm struggling to find the data source that gene.iobio uses to display the phylop conservation scores for a given gene.  E.g. phyloP7way, phyloP100way etc?

**Comment by danielprosser1** [comment]
Closing since I found my trial and error it was hg38.phyloP100way.bw

**Comment by tonydisera** [comment]
Hi Daniel -
Thanks for posting your question. I will put the version info for phyloP on our 'About' dialog.
Tony
