### ISSUE TITLE
Need to refresh gene2pheno db when HPO releases new gene-to-phenotype file

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#165]
See #844

**Comment by AlistairNWard** [comment]
If this is an issue that causes us to go out of date, then we should address it.

**Comment by mvelinder** [comment]
I added this to the current sprint, we need to address it or clarify that it is being updated before the paper release

**Comment by AlistairNWard** [comment]
@tonydisera to check what is still needed
