### ISSUE TITLE
Organize eutils for gene summary requests such that max request limit not reached

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#227]

**Comment by tonydisera** [comment]
example: (("RAI1"[Gene Name] OR "MYLK2"[Gene Name]))

**Comment by AlistairNWard** [comment]
@tonydisera This is many years old. Is it a current problem?

**Comment by tonydisera** [comment]
Yes, we made this change back in Oct of 2019.  We now use a multi-gene query to minimize the number of requests.  I am closing this issue.
