### ISSUE TITLE
Update clinvar vcf served from backend.iobio.io on a weekly basis

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#375]
We need some way to automatically update the vcf from clinvar on a weekly basis

**Comment by mvelinder** [comment]
From my understanding the newest one is always at 
https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz
https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar.vcf.gz
respectively

for easy curling

**Comment by anderspitman** [comment]
I think the first step is probably switching to a generic name for the paths. They're currently date-specific like this: `/static/GRCh38/2019/clinvar_20191021.vcf.gz`. @tonydisera, would something like `/static/clinvar/GRCh38/clinvar.vcf.gz` work? If that's ok, I'll go ahead and add that to the current deployment, then you can update the frontend to start using it. Then I can remove the old ones and automate the updates to continually update those files with the latest.

**Comment by anderspitman** [comment]
@tonydisera @mvelinder I have added the latest clinvar files to the backend, accessible like this:

`backend.iobio.io/static/clinvar/GRCh38/clinvar.vcf.gz`

It's available on both AWS and PE deployments. Once @tonydisera has time to switch gene over we can remove the old ones and close this.

**Comment by anderspitman** [comment]
Oh and I'll be doing the weekly updates manually for now. It won't require any ongoing changes to the code, simply running the deployment script.

**Comment by mvelinder** [comment]
> @tonydisera @mvelinder I have added the latest clinvar files to the backend, accessible like this:
> 
> `backend.iobio.io/static/clinvar/GRCh38/clinvar.vcf.gz`
> 
> It's available on both AWS and PE deployments. Once @tonydisera has time to switch gene over we can remove the old ones and close this.

@anderspitman this is great. We'll want an equivalent GRCh37 one as well, my previous comment has the ftp link for the GRCh37 VCF

**Comment by anderspitman** [comment]
GRCh37 is available as well, you just need to adjust the URL.

**Comment by tonydisera** [comment]
Thanks  Anders!!

**Comment by mvelinder** [comment]
Thanks @anderspitman just making that function was available. This is great!

**Comment by mvelinder** [comment]
Definitely needs to be addressed or clarified that this is happening before the paper release

**Comment by anderspitman** [comment]
I think we ended up deciding on monthly, right? Every first Friday or something like that. In any case, with gru being 1.0+ now and deployments based on docker, I think we're ready to set up a regular release schedule. I'd still prefer monthly, but we can do weekly if necessary. I'm make a note to set this up soon after I get back so everything is fresh when the paper hits.
