### ISSUE TITLE
The Utah Mosaic http endpoints (e.g. geneinfo, genomebuild) seem to fail intermittently

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#418]
As a workaround, I'm pointing these endpoints to AWS (https://backend.iobio.io/geneinfo, https://backend.iobio.io/genomebuild)

**Comment by anderspitman** [comment]
@tonydisera I wonder if this could have something to do with running on Lustre. Maybe sqlite makes a lot of small requests to the filesystem, and when latency spikes on the Lustre cluster we're seeing issues? IDK just a thought I wanted to write down.

**Comment by anderspitman** [comment]
@mvelinder @tonydisera can we merge this with #400 somehow? They look the same to me...

**Comment by anderspitman** [comment]
I'm going to remove this from the 4.0 release since we have a temporary solution.

**Comment by tonydisera** [comment]
Cool.

**Comment by anderspitman** [comment]
I'm closing #400, but it still has a couple comments on it that may be useful for reference.

**Comment by mvelinder** [comment]
Seems fixed based on the comment from Anders

**Comment by anderspitman** [comment]
I think we should leave this one open, since we haven't verified that the Mosaic endpoints work (it's still hard-coded to use backend.iobio.io).

**Comment by AlistairNWard** [comment]
@anderspitman What is the status of this?

**Comment by anderspitman** [comment]
Good question. I just did a quick check and we're definitely still using the backend.iobio.io endpoints. It would probably be worth trying to switch back and see if it works now. We're running off an SSD now which might solve whatever the problem was.

**Comment by AlistairNWard** [comment]
@tonydisera to verify if still happening

**Comment by tonydisera** [comment]
I tested this and didn't see any problems with these services failing in the mosaic backend.  I'm closing this issue.

**Comment by anderspitman** [comment]
@tonydisera when launching gene.iobio from Mosaic, it still looks like it's using backend.iobio.io endpoints for these requests. It would be nice to make it use the same backend as the other requests. It's more scalable and maintainable that way. For example, Nebula gene is also using backend.iobio.io for geneinfo and genomebuild.

**Comment by anderspitman** [comment]
I believe all that's necessary is removing this line, right?

https://github.com/iobio/gene.iobio/blob/5ed22d7661b0254c3da1dc33f1c836197a483c98/client/app/globals/GlobalApp.js#L121

I just tested that against a local backend and it seems to work.
