### ISSUE TITLE
The production build of gene.iobio is still very bloated.  Figure out how to add back in minimize.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#458]

**Comment by tonydisera** [comment]
I'm not sure if this is part of the problem, but I had to comment out Uglify in webpack.config.js.
```
 /* Had to remove due to problems with production build
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    */
```

**Comment by adityaekawade** [comment]
I have not tried this, but I think another reason might be the data files
which are imported. For example genes.json is quite big. I will look into
it.

**Comment by tonydisera** [comment]
Thanks Adit for volunteering.  I think genes.json would just be served from a separate directory that is part of the gene.iobio client directory structure.  

I'm wondering why dist.js is still so big.  It seems like it should shrink down to < 10 MB.

Thanks!

**Comment by tonydisera** [comment]
Here is the size of dist.js (test mode):
<img width="553" alt="Screen Shot 2020-04-11 at 7 10 12 PM" src="https://user-images.githubusercontent.com/8420103/79058233-80d1f180-7c28-11ea-8b28-358e30d51d3f.png">

<img width="642" alt="Screen Shot 2020-04-11 at 7 12 28 PM" src="https://user-images.githubusercontent.com/8420103/79058238-8e877700-7c28-11ea-866f-d8c5bb408862.png">
And when we build dist.js (prod mode):

**Comment by adityaekawade** [comment]
Even though genes.json is in a separate `data` directory, we are still importing genes.json in `GeneHome.vue` which gets added to the build.js. 

 
<img width="673" alt="Screen Shot 2020-04-12 at 10 27 14 AM" src="https://user-images.githubusercontent.com/16284713/79075520-342dfb00-7ca8-11ea-88a0-8b7811c60f9a.png">


This is the build.js size when I run the build command in production by importing genes.json 
<img width="689" alt="Screen Shot 2020-04-12 at 9 52 14 AM" src="https://user-images.githubusercontent.com/16284713/79074834-6a1cb080-7ca3-11ea-8b06-d26d4a82c835.png">


If I comment out the import of the file and run the build command, I immediately see a difference of 6 MB.
<img width="686" alt="Screen Shot 2020-04-12 at 9 54 15 AM" src="https://user-images.githubusercontent.com/16284713/79074859-9fc19980-7ca3-11ea-9ab8-5f9608a00119.png">
 
I guess we can store these static JSON files on the server (S3 bucket?) and make a fetch request when the component (`GeneHome`) is created.

**Comment by tonydisera** [comment]
Interesting.   Thanks for looking into this @adityaekawade!  It sounds like we might be able to remove this from the build.js.  Nice detective work!

**Comment by anderspitman** [comment]
This is similar to what I did to optimize bam.iobio. The bed file (4.5MB) was being packaged into build.js as above. Rather than importing it in webpack, I changed it to a fetch request when the bed link is hit. I just moved the bed file into `client/data/`, so when you deploy it's available on the same S3 bucket as the rest of the app. Final size of bam.iobio is 3.5MB.

**Comment by anderspitman** [comment]
@tonydisera another thing I've been meaning to mention is gene.iobio still has a bunch of cruft left over from local file support. We should be able to remove a bunch of the bgzf, compression, binary.js, inflate, deflate, etc stuff.

**Comment by AlistairNWard** [comment]
@anderspitman Should we close this?

**Comment by AlistairNWard** [comment]
I'm not sure if it's connected, but I've launched gene a few times recently and it's taken a long time (almost a minute), just to get the landing page. Basically it's just a gray screen for a long time

**Comment by AlistairNWard** [comment]
@tonydisera Look into how big this is

**Comment by tonydisera** [comment]
The build.js for the production build is 16 M, compared to 48 M for the dev build.  For now, let's not worry about the size of the build.  I will close this issue.
