### ISSUE TITLE
Multialign is making extra CORS preflight requests

### ISSUE THREAD

**Issue by anderspitman** [iobio/gene.iobio#495]
I noticed that the multialign requests are being preflighted. It shouldn't be necessary since I believe these qualify as ["simple CORS requests"](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests). Looks like the culprit is that the content type of the request is set to "text". I think if we change it to "text/plain" it will fix this. Relevant code is here: https://github.com/iobio/gene.iobio.vue/blob/c46f57f5f7b363979fec31b11b01c35f69be70d7/client/app/models/MultiAlignModel.js#L60

**Comment by AlistairNWard** [comment]
@anderspitman Does this still need doing?

**Comment by anderspitman** [comment]
Yep. Worth doing and should be a quick fix.

**Comment by AlistairNWard** [comment]
@anderspitman @tonydisera Is this still a quick fix worth doing?

**Comment by anderspitman** [comment]
I'll defer to @tonydisera on this.

**Comment by tonydisera** [comment]
Oh @anderspitman, nice catch!  You understand CORS.  I am impressed, my friend.  Changing to text/plain content type got rid of the pre-flight requests!

**Comment by anderspitman** [comment]
@tonydisera awesome, glad it worked. I think we can close this @AlistairNWard
