### ISSUE TITLE
There are duplicated genes in the sqlite db for the geneinfo service.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#502]
It looks like GRCh37 gencode has < 300 dups, but that GRCh37 refseq, GRCh38 refseq, and GRCh38 refseq have ~35,000 dup genes.
```
3:25
(base) Tonys-MacBook-Pro:geneinfo_service tony$  grep refseq dups_37.txt | wc -l
   31664
(base) Tonys-MacBook-Pro:geneinfo_service tony$  grep gencode dups_37.txt | wc -l
     289
(base) Tonys-MacBook-Pro:geneinfo_service tony$ 
(base) Tonys-MacBook-Pro:geneinfo_service tony$  grep refseq dups_38.txt | wc -l
   37064
(base) Tonys-MacBook-Pro:geneinfo_service tony$  grep gencode dups_38.txt | wc -l
   36282
(base) Tonys-MacBook-Pro:geneinfo_service tony$ 
```

**Comment by tonydisera** [comment]
```
(base) Tonys-MacBook-Pro:geneinfo_service tony$ sqlite3 gene.iobio.db "select gene_name, build, source, count(*) from genes group by gene_name, build, source having count(*) > 1;" > gene_names_dup.txt
(base) Tonys-MacBook-Pro:geneinfo_service tony$ sqlite3 gene.iobio.db "select gene_name, build, source, count(*) from genes group by gene_name, build, source having count(*) = 1;" > gene_names_unique.txt
```

**Comment by tonydisera** [comment]
This is actually a problem.  Notice how the transcripts are different for RAI1 GRCh38 gencode:
Screen Shot 2020-05-01 at 3.16.58 PM.png 
Screen Shot 2020-05-01 at 3.16.58 PM.png


If I were to guess, I think that GRCh38 gencode was imported with one version of the gff and then later with another version.
Maybe the same happened with GRCh37 (refseq).

<img width="1475" alt="Screen Shot 2020-05-01 at 3 16 58 PM" src="https://user-images.githubusercontent.com/8420103/80843188-e3cbfe00-8bc0-11ea-85c7-24967f46abfc.png">

**Comment by AlistairNWard** [comment]
@AlistairNWard needs to finish building a gene db

**Comment by AlistairNWard** [comment]
@tonydisera Do we need to discuss this?

**Comment by AlistairNWard** [comment]
@tonydisera to check if this is still an issue

**Comment by tonydisera** [comment]
We should probably hold off on fixing this since it isn't causing any problems right now.  When we rework the gene aliases, let's load the db from the source gffs to create a clean version of the db.
