### ISSUE TITLE
Define sex to proband when loading from URLs

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#680]
If you load from URLs there is no way to define the sex  of the proband. With the latest changes you get a diamond because sex is not defined 

![image](https://user-images.githubusercontent.com/22081541/100287199-75220980-2f31-11eb-902a-a8ac48506948.png)

We could pretty easily add a male/female dropdown option for proband in the file loading menu

**Comment by AlistairNWard** [comment]
Agreed, but not a high priority
