### ISSUE TITLE
The transcript (dropdown button) label in the Genes panel is slow to refresh, showing old transcript from prev selected gene.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#709]
Run demo data.  After analyze all has completed, we see the RAI1 gene with the appropriate canonical transcript.
<img width="582" alt="Screen Shot 2020-12-22 at 9 49 24 AM" src="https://user-images.githubusercontent.com/8420103/102912900-394c6800-443b-11eb-8cd6-6b2ffd7dfcc1.png">

Now click on next variant in side panel, PDHA1.  Hmm... The gene panel shows PDHA1, but the transcript shown is still for RAI1.

<img width="1239" alt="Screen Shot 2020-12-22 at 9 49 28 AM" src="https://user-images.githubusercontent.com/8420103/102913175-a65ffd80-443b-11eb-82c0-2d60a00e360f.png">

A few seconds later, we see the transcript label refreshed with transcript for PDHA1.

<img width="581" alt="Screen Shot 2020-12-22 at 9 49 40 AM" src="https://user-images.githubusercontent.com/8420103/102913287-cbed0700-443b-11eb-8f38-fa715d87d612.png">

What is the lag all about?  If we can't get rid of the lag, we should at least hide the prev transcript label until it is correctly refreshed.

**Comment by AlistairNWard** [comment]
A number of things fall into this bucket. For example, click on TTN. It takes a while for this to come in. In the meantime, we still see the coverage for the previous gene etc.

**Comment by AlistairNWard** [comment]
Some of this is probably a lot of effort, but we want to avoid misleading information. What could be done before paper release to minimize confusion to the user?
