### ISSUE TITLE
Error message for expired links

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#714]
People could launch gene from Nebula / Mosaic then go away and come back later on. If the file URLs have expired in the meantime, gene will no longer work. We should probably catch this

**Comment by mvelinder** [comment]
I ran into this back when GNOMEXEEEEE links would expire

**Comment by AlistairNWard** [comment]
Is this easy to implement?

**Comment by AlistairNWard** [comment]
Improve the error messages to provide the user with some steps they can take (e.g. refresh browsers) prior to reaching out for help
