### ISSUE TITLE
Sequence coverage Quality visualization doesn't display when launching from Mosaic using a single gene 

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#745]
Launch https://mosaic.chpc.utah.edu/#/projects/536/samples/ using the gene AIFM1 - gene should default to the X-linked recessive missense variant chrX:130140554 C->T

However, the Quality doesn't display

![image](https://user-images.githubusercontent.com/22081541/121567439-cf6d4e00-c9db-11eb-9746-3c80cdd0b986.png)

Click to a different variant in the gene and then click back to the X-linked variant and the visualization does display now 

![image](https://user-images.githubusercontent.com/22081541/121568062-7d78f800-c9dc-11eb-884c-7237eb672259.png)

The visualization loads fine when launching gene.iobio from Mosaic using a gene list (can use Skeletal dysplasia panel gene list - which contains AIFM1)

![image](https://user-images.githubusercontent.com/22081541/121568268-c16bfd00-c9dc-11eb-8ccb-33a9bf9f9a77.png)

Also, notice the **coverage calculated is different depending on the mode launched**... which is also not great

**Comment by AlistairNWard** [comment]
I just launched and the coverage visual seems to be fixed.

But there remains a difference between the coverage shown in the different panels. This is a clear error and needs to be fixed.

**Comment by AlistairNWard** [comment]
This is quite important to understand how the coverage value is inconsistent.

**Comment by tonydisera** [comment]
@AlistairNWard, the 55x showing in the coverage depth area chart in the Variants card is the bam depth. The 61x showing in the variant inspect card is the variant read count (alt + ref) in the vcf, reported by the variant caller. 

<img width="859" alt="Screen Shot 2022-07-19 at 10 09 08 AM" src="https://user-images.githubusercontent.com/8420103/179798698-e8881e59-af86-4192-99f4-9bfef6cb26ea.png">

But something strange happens. If I click on the variant symbol in the Variants card, the QC now shows the bam depth, not the total read count.

<img width="175" alt="Screen Shot 2022-07-19 at 10 09 17 AM" src="https://user-images.githubusercontent.com/8420103/179798722-bcb3be7c-4d40-4a17-bb43-fc4483f64614.png">
