### ISSUE TITLE
Show variants by category

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#758]
We can show by inheritance, but would be good to filter by category. Then, if a user created a filter, they could limit the view to just those variants.

This is something Barry mentioned for cases he looks at in NeoSeq. Sometimes there are genes that are really interesting and he wants to scour all the intronic variants. He can create a custom filter, but can't reduce the variants in the view to just those variants.

**Comment by AlistairNWard** [comment]
Maybe this would just be adding the eyeball icon to categories to view / hide variants in the category?

**Comment by tonydisera** [comment]
I like the idea of limiting the variants card to only show those variants passing the filter, but I don't think the user will notice the toggle on the filter (left side bar, grey 'header') area. How about if we have a 'Show filtered variants only' on the variants view?  When the user clicks on the gene, we show all variants and hide the toggle. When the user clicks on the filtered variant, we show only those variants passing the filter by default and show the 'Show filtered variants only', toggled on. If the user toggles this button off, all variants appear.
