### ISSUE TITLE
Update Mosaic integration for all apps

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#764]
Mosaic now has an `experiments_ids` query parameter. When requesting files from Mosaic, we currently just use the sample_id to get the files for the sample. Some samples have multiple bam / vcf files, and currently the iobio apps are getting a random file. This causes periodic failures, or results discrepancies. When samples have multiple files, they are now organized into experiments, so a combination of sample_id and experiment_id will give unique files. The launch modals have been updated to allow the user to pick the experiment, so the apps will have both ids required to get the unique set of files.

**Comment by adityaekawade** [comment]
Which project and sample in mosaic.frameshift.io have the experiment id? I tried the "Sample exomes" project with all the samples and "1000 Genome project" with few samples. But I didn't find a sample that has experiments associated with it. And so when I launched gene.iobio there was no experiment id as a query parameter. Also, how can I create an experiment?

**Comment by AlistairNWard** [comment]
It's `Platinum Experiment Test` (76). I just added you to the project, so you should be able to see it now
