### ISSUE TITLE
Change local file input window to include fields for both files and indexes or add explanation about how to select multiple files

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#781]
Ideally we can replace the single input dialog  window with a field for each file (the VCF and the TBI, the CRAM and CRAI), but if that's too much work, I think we should add a message that says "On most systems you can hold Shift and then click each file to select multiple files". It should go in this warning pane for both VCF and BAM/CRAM errors

![image](https://user-images.githubusercontent.com/22081541/129785233-1c17193e-391a-461a-9aa6-b915e65766a3.png)

**Comment by tonydisera** [comment]
@adityaekawade , I think this fix broke the local file validation.  I can now select .jpg files as well as three files, and no warning message appears.  Can you backout this fix?

**Comment by tonydisera** [comment]
Hi Adit - I looks like local file validation is no longer working.  I was able to select 3 files and files of the incorrect type without warning.  
<img width="874" alt="Screen Shot 2021-08-24 at 2 31 09 PM" src="https://user-images.githubusercontent.com/8420103/130686348-bd179904-0610-4e2f-a4e9-89208c8fef9f.png">

**Comment by AlistairNWard** [comment]
We should check all the local file stuff, but it's lower priority
