### ISSUE TITLE
Add cram to file input window

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#782]
Need to show up front that that crams are also supported

![image](https://user-images.githubusercontent.com/22081541/129811053-f93f9d15-001f-42dc-8c9f-f5055607928c.png)

Just change this "Enter bam URL (optional)" text to "Enter bam/cram URL (optional)"

And likewise change "Enter bai URL (optional)" text to "Enter bai/crai URL (optional)"

**Comment by AlistairNWard** [comment]
Yep, make it clear everywhere bam is mentioned, that it could be bam/cram
