### ISSUE TITLE
Variant tracks and annotations are not reloaded when VCFs are removed from the file input windows

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#784]
On production, load the demo data and let it load the variants, then open the file input window and remove the VCF and TBI for each sample, then click Load -- and the variants are still present in the variant track. They are not called variants but seem to be the same variants from the VCF, as if the view is not being refreshed after the data inputs have changed.

![image](https://user-images.githubusercontent.com/22081541/130072838-d8f0aeb5-6e48-4191-8a3d-6cdb8022f8a9.png)

**Comment by AlistairNWard** [comment]
Make sure that any changes in the files modal are enacted when submitted
