### ISSUE TITLE
Signed URLs from public Mosaic result in warning on Load dialog; continue button does nothing

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#788]
Launch a project from Mosaic public (https://mosaic.frameshift.io/).  Now click on the 'Files' button in the nav bar.  Now click on the 'Load' button.  The following message appears and the continue button doesn't work.
<img width="1591" alt="Screen Shot 2021-08-24 at 3 04 14 PM" src="https://user-images.githubusercontent.com/8420103/130691091-f4e7eb9c-4e3f-4bf2-b410-83f91aafcda2.png">
<img width="530" alt="Screen Shot 2021-08-24 at 3 04 21 PM" src="https://user-images.githubusercontent.com/8420103/130691102-dcf7a405-16e0-4e34-90a8-b16abd3c46dd.png">

**Comment by AlistairNWard** [comment]
@tonydisera We should talk about this one. Zilton (in Brazil) has created some public urls and I see this same issue:

**VCF:**
https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/HaplotypeCaller_IDP30.vcf.gz?sp=r&st=2022-04-27T20:05:43Z&se=2023-04-28T04:05:43Z&sv=2020-08-04&sr=b&sig=TJ3UuYP1mOUjGVm8W8T79dUJsAdwMCWFD52Iwhsare0%3D

https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/HaplotypeCaller_IDP30.vcf.gz.tbi?sp=r&st=2022-04-27T20:07:03Z&se=2023-04-28T04:07:03Z&sv=2020-08-04&sr=b&sig=3ohSMdqxRGQQYUwoMvu1gmWZttBNC68tEsbVCq%2FpAps%3D

**BAM:**
https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/IDP30_1.bam?sp=r&st=2022-04-27T20:07:30Z&se=2023-04-28T04:07:30Z&sv=2020-08-04&sr=b&sig=Su6t9uuVRpYUQ9w12zVrceUHWIKXGKrlKurZ8HJuEE8%3D

https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/IDP30.bam.bai?sp=r&st=2022-04-27T20:08:00Z&se=2023-04-28T04:08:00Z&sv=2020-08-04&sr=b&sig=ILcuEjBSDWI1IOzmcD%2FitAmY3xkLkC2wLki%2FtGZgk1o%3D

**Comment by AlistairNWard** [comment]
These are the newest urls:

VCF_URL
https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/HaplotypeCaller_4945_21.vcf.gz?sp=r&st=2022-05-03T18:41:03Z&se=2023-05-04T02:41:03Z&sv=2020-08-04&sr=b&sig=7wgPeNQlc8VZDRwiaUIEptPOItTtpk%2B9HX%2BZjaE60%2Bc%3D

TBI_URL
https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/HaplotypeCaller_4945_21.vcf.gz.tbi?sp=r&st=2022-05-03T18:41:25Z&se=2023-05-04T02:41:25Z&sv=2020-08-04&sr=b&sig=y%2B036oU%2B2u%2B33sPC3uMqQnKc1MZvx%2FKnJKgsdTjI8%2FY%3D

BAM_URL
https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/4945_21.bam?sp=r&st=2022-05-08T21:46:43Z&se=2023-05-09T05:46:43Z&sv=2020-08-04&sr=b&sig=9d7xBY%2FpRIEjJ7C18LsJZ4YkyvcvGYgWiycpz5SYB7I%3D

BAI_URL
https://stggenomasraros.blob.core.windows.net/genomas-raros/clin_iobio/4945_21.bam.bai?sp=r&st=2022-05-08T21:47:16Z&se=2023-05-09T05:47:16Z&sv=2020-08-04&sr=b&sig=TISGztHiN%2BH0GPoiW1WRe2ag%2B8LwBoO40yHdkGxFm0o%3D
