### ISSUE TITLE
Update ACMG genes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#794]
ACMG updated the list of secondary findings genes to 73 (Genetics in Medicine (2021) 23:1381–1390; https://doi.org/10.1038/s41436-021-01172-3)

- [ ] Change the name of _ACMG 59_ in the gene list to _ACMG SF v3.0 (73)_
- [ ] Update the list to the 73 genes
- [ ] What would be a good process for keeping this list up-to-date? ACMG expects to update the list annually every January

ACTA2
ACTC1
ACVRL1
APC
APOB
ATP7B
BMPR1A
BRCA1
BRCA2
BTD
CACNA1S
CASQ2
COL3A1
DSC2
DSG2
DSP
ENG
FBN1
FLNC
GAA
GLA
HFE
HNF1A
KCNH2
KCNQ1
LDLR
LMNA
MAX
MEN1
MLH1
MSH2
MSH6
MUTYH
MYBPC3
MYH11
MYH7
MYL2
MYL3
NF2
OTC
PALB2
PCSK9
PKP2
PMS2
PRKAG2
PTEN
RB1
RET
RPE65
RYR1
RYR2
SCN5A
SDHAF2
SDHB
SDHC
SDHD
SMAD3
SMAD4
STK11
TGFBR1
TGFBR2
TMEM127
TMEM43
TNNI3
TNNT2
TP53
TPM1
TRDN
TSC1
TSC2
TTN
VHL
WT1

**Comment by mvelinder** [comment]
Do they publish them at an expected URL or file location? I have not seen that. I've only seen the gene names in a publication that we have to manually grab. Obviously it'd be easier if they had an http://acmg.org/acmg-list/current.genes.txt or something easy to grab

**Comment by AlistairNWard** [comment]
Not to my knowledge. They just want to publish annually, but January was as committed as they got.

**Comment by tonydisera** [comment]
fixed gene_4.6.2_2021-09-28
