### ISSUE TITLE
Genes and variants not removed when removing gene list

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#801]
Load demo data, let it finish loading, click the genes list and remove all genes, click Apply, the genes and variants

![image](https://user-images.githubusercontent.com/22081541/137957700-0232a0e7-9d27-49f4-9b8d-2d7df295eccf.png)

**Comment by AlistairNWard** [comment]
Agreed. If you clear the list, it clears the genes list, but no other parts of the app. Make sure the whole thing is cleared, and probably prompt for a gene to be entered. Alternatively, we could require that at least one gene needs to be in the list in order to submit
