### ISSUE TITLE
Review saving variants

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#807]
We received feedback on saving variants as being suboptimal. We need to review the process of saving variants and ensure it is easy, understandable and generates sensible output files.

**Comment by AlistairNWard** [comment]
As part of the gene.iobio overhaul we will consider changing data structures for saving information, including saving information to Mosaic. Figure out how we want saving to work

**Comment by tonydisera** [comment]
@AlistairNWard, yeah, this was never an ideal solution. We save variants in a Mosaic blob for 'Analysis'. It seems like it would be better to have a list of variant ids that point back to a variant set in Mosaic.  I look forward to discussing a better solution.

**Comment by AlistairNWard** [comment]
We can scope this out when we get confirmation of the grant focused on this. At that point, we'll want to look at saving to Mosaic (which could also just save the blob to file) and saving to vcf as the two main options. We can then include things like the comments etc. I'll look over the current ui and see what we need to improve
