### ISSUE TITLE
Badges are clipped to the next row

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio#823]
![image](https://user-images.githubusercontent.com/22081541/166942366-86691a76-54ba-471a-a90a-b13b56ab2fd0.png)

**Comment by AlistairNWard** [comment]
Can you provide some information on how to reproduce this, @mvelinder? I don't see this behaviour

**Comment by jdy4389** [comment]
I can't speak for them but I see the same thing on Firefox 99/100 (but not in Chrome)
![image](https://imgur.com/KskPdwH.png)

**Comment by AlistairNWard** [comment]
Thanks @jdy4389 .

This is a firefox specific issue
