### ISSUE TITLE
Variant not showing up

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#824]
Launch gene from the APOA1 variant set in the following project. The variant set contains one variant (1bp insertion) in the APOA1 gene, but the variant doesn't show up in gene.

https://mosaic.chpc.utah.edu/#/projects/923/variants/sets

**Comment by AlistairNWard** [comment]
I'm now finding that when I launch from Mosaic using the variant set, gene.iobio prompts me for genes. So it seems like there are two ways to launch:
1. Launch from Mosaic into APOA1. The variant at position 11:116837115 doesn't show up in gene
2. Launch from the variant set containing this variant, and gene prompts you to enter a gene

There is another variant that seems to be missing in CLCN6 - 1:11827090

**Comment by tonydisera** [comment]
@AlistairNWard, I noticed that this issue was re-opened. Fair enough. How should we address this issue in gene.iobio? How should gene.iobio deal with variants in a variant set that don't apply to the proband? Also, I'm wondering why I can't launch gene.iobio from Mosaic for the father.  I'm going to create a separate issue for the launching non-proband problem.

**Comment by AlistairNWard** [comment]
I thought I'd added a comment to this when I reopened. Turns out that I didn't click submit.

The problem with not being able to a non-proband sample when launched from Mosaic is actually a gene.iobio problem - which is why I reopened it. As an example, go to https://mosaic.chpc.utah.edu/#/projects/476/samples/, select Dad (NA12891), launch gene.iobio. Click Individual and the select Dad from the pedigree. The samples dropdown at the top is populated with NA12891. 

![Screen Shot 2022-06-09 at 9 24 18 PM](https://user-images.githubusercontent.com/523111/172971586-98d4185e-53d1-4b68-9341-08c2ad554917.png)

Pick a gene and launch gene. 

![Screen Shot 2022-06-09 at 9 25 54 PM](https://user-images.githubusercontent.com/523111/172971744-1ca87460-aee8-4052-acf4-6af576c88b25.png)

You can see that the variants are still being shown for the proband, but if you look in the url, the `sample_id` is 19864. If you go back to Mosaic and click on the samples, you can see that `sample_id` 19864 corresponds to NA12891. NA12878, which gene is showing, is 19863. So Mosaic is passing the correct `sample_id` to gene, but gene isn't using it.
