### ISSUE TITLE
Data masking

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#825]
For sharing data with collaborators, David Adams suggested that it would be beneficial to allow "masking" so that the entire genome isn't shared. The goal would be to only allow gene.iobio to pull in data from "allowed" genes. We can discuss methods, but one potential way would be to supply a gene whitelist via text file, Mosaic etc, and only genes from this list could be interrogated.

**Comment by tonydisera** [comment]
@AlistairNWard, I agree. The gene white-list is the most straightforward way to mask the genome.  Good idea.

**Comment by AlistairNWard** [comment]
Sweet. We can scope this out in an iobio meeting at some point. I'll probably get a chance to talk to David Adams in person at the end of June, so I'll touch base with him about whether this is still important to him and have a proposal I can discuss with him.
