### ISSUE TITLE
Cannot launch gene.iobio for non-proband.

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#831]
This is related to #824.  I can't launch gene.iobio for the father.  

https://mosaic.chpc.utah.edu/#/projects/923

I select the father, launch gene.iobio, and select 'Individual'. Mosaic launches with the correct sample id.
<img width="841" alt="Screen Shot 2022-06-09 at 6 20 35 PM" src="https://user-images.githubusercontent.com/8420103/172966418-a0cdaec9-5ad5-475f-9112-0226f819efc9.png">
<img width="1273" alt="Screen Shot 2022-06-09 at 6 21 13 PM" src="https://user-images.githubusercontent.com/8420103/172966642-b7c07033-cdaf-4e57-aa4e-372945e1ddc4.png">

**Comment by AlistairNWard** [comment]
Ha. This was exactly why I reopened #824. I just added a whole bunch of stuff to that issue explaining what you have already explained here! I'll close #824 again since it was this issue that caused me to reopen it

**Comment by tonydisera** [comment]
When 'Individual' is selected, Mosaic sends in a launch parameter is_pedigree=false. For some reason, gene.iobio no longer pays attention to this parameter.  I'm changing the code so that is_pedigree=false will force gene.iobio to launch with the selected sample and not try to look up the proband based on the pedigree.
