### ISSUE TITLE
Integrate gene:phenotype associations

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#844]
**3.2.1. Integrate gene:phenotype associations into gene.iobio**
- Build **_reusable_** visual components that will allow users to view HPO and disease associations for the gene alongside those defined for the patient (extracted from Mosaic). 
- A summary of associations will be provided in gene.iobio’s main view (Figure 1B), which will be selectable to provide the full analysis. The view will show the patient’s HPO terms, and clearly mark which are associated with the current gene. If the gene is associated with a close relative of a patient HPO term (e.g. is a parent or child), this relationship will be highlighted. All patient HPO terms will be displayed, so those with no association to the present gene can be weighed alongside those that do - important for performing a differential diagnosis.

![Asset 11](https://user-images.githubusercontent.com/523111/182190494-4aaad3a0-8e00-4a5d-8406-a477f729c489.png)

**Comment by tonydisera** [comment]
@AlistairNWard - Will Mosaic store both the Patient:HPO terms and the Gene:HPO terms? Also, will this component be reusable by both Mosaic and gene.iobio?

**Comment by AlistairNWard** [comment]
Yes, Mosaic should have both. The plan is that there will be a table including all HPO terms. For each project, the patient HPO terms will then be stored. In the initial implementation, we probably won't have the HPO->gene associations, but there is a single file that contains these associations. In order to ensure gene.iobio isn't completely Mosaic dependent, we probably just want to pull the patient terms from Mosaic and then use the file to get the associated genes. 

The files are called genes_to_phenotype.txt and phenotype_to_genes.txt and can be found here:
https://github.com/obophenotype/human-phenotype-ontology/releases/latest

**Comment by tonydisera** [comment]
We need to have a batch process that updates the gene_to_phenotypes.db in the iobio gru backend. 

I noticed that the files are also hosted here:
http://purl.obolibrary.org/obo/hp/hpoa/genes_to_phenotype.txt
http://purl.obolibrary.org/obo/hp/hpoa/phenotype_to_genes.txt

**Comment by tonydisera** [comment]
Getting the gene:disease associations will be a bit trickier. It looks like this data comes from OrphaNet. (http://www.orphadata.org/cgi-bin/index.php)

There is an XML file that we will need to parse and load into a db. Fortunately, the XML format is straight-forward; however, given than XML imposes a hierarchy, the file is organized by disease. Within each disease is a list of associated genes.  

I propose that we use the existing sqlite db hpo_gene_to_phenotypes.db that is used by the iobio gru backend service gene2pheno (example: https://backend.iobio.io/gene2pheno/api/gene/RAI1). We can add a new table and endpoint for the gene:disease associations.
