### ISSUE TITLE
Communication features

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#850]
**3.3.4. An effective genomic communication platform**
- Extend Mosaic conversations so they can be associated with saved entities including individual variants, genes, sets of genes, charts, analyses (made using tools including gene.iobio, IGV, or any other of the tools available within Mosaic)

**Comment by AlejandroR44** [comment]
what is used in order to create web technologies? programming languages and markup languages? Or that and coding languages?

**Comment by AlistairNWard** [comment]
I'm not exactly sure what you are asking, but gene.iobio makes use of multiple languages, bioinformatic tools, frameworks etc. Specifically, we use javascript, Vue etc.
