### ISSUE TITLE
gnomAD - Broken? Links for Variant - gnomAD and dbSNP

### ISSUE THREAD

**Issue by zorgster** [iobio/gene.iobio#871]
**gnomAD - affects specific rsIDs:**

The issue is for variants that are not found in v2.1.1 but found in v3.1

The Variant - ExternalLinks routes you to :  https://gnomad.broadinstitute.org/variant/11-128485068-T-C
-> Error:  **Variant not Found!**

The link_out under **Population Frequency** adds the correct dataset variable:
https://gnomad.broadinstitute.org/variant/chr11-128485068-T-C?dataset=gnomad_r3

**dbSNP - all SNPs?**
The URL is not working for any SNP (it is broken from gnomAD's page too)
URL :  https://www.ncbi.nlm.nih.gov/projects/SNP/snp_ref.cgi?rs=rs142279599
This URL works as expected :  https://www.ncbi.nlm.nih.gov/snp/rs142279599

**Comment by AlistairNWard** [comment]
Thanks for the comments!

The dbSNP links have all been fixed. If you are launching gene.iobio from Nebula, however, this version has not yet been updated.

@tonydisera The gnomAD link that fails is under external links. Since we have a direct link in the gnomAD section, maybe we should just remove the link from the external links section?

**Comment by zorgster** [comment]
Hi... yes it is the version from Nebula and I suspected that there'll be a delay before changes pass through...  (for both issues..)

**Comment by AlistairNWard** [comment]
We should be updating the Nebula version today, so hopefully the dbSNP fix should be there asap!

**Comment by zorgster** [comment]
The addition of r3 is determined by the reference coordinates... The genomic position is in GRCh38 not GRCh37, so it should have the dataset=gnomad_r3.  GRCh37 do not need it and go to v2.1.1.

**Comment by zorgster** [comment]
so perhaps it just needs to check the build (me.genomeBuildHelper.getCurrentBuildName?) around line 1682 in GeneModel where the gnomad link is constructed? and then append the additional variable?

https://github.com/iobio/gene.iobio/blob/master/client/app/models/GeneModel.js

**Comment by zorgster** [comment]
Hi
I reported the dbSNP to gnomAD as well.  At the time I asked them what happens later when dataset_r4 is released.  They said that it would be better (now) to explicitly specify dataset=gnomad_r2 for GRCh37 and gnomad_r3 for GRCh38.   They have not yet decided on what will happen when everything is combined in release 4.  But if the default is changed to gnomad_r4, then all calls without a specific dataset may end up in the wrong place (until it is fixed).

**Comment by tonydisera** [comment]
> The addition of r3 is determined by the reference coordinates... The genomic position is in GRCh38 not GRCh37, so it should have the dataset=gnomad_r3. GRCh37 do not need it and go to v2.1.1.

Good catch Oliver! I will fix this in the next release (4.6.12).
