### ISSUE TITLE
Handle new gnomAD fields in variants sets (when launched from Mosaic)

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#878]
There are following new gnomAD v2 fields:
If we want to use v2.1.1 genomes, we need the following:
gnomad_allele_count__v2_1_1_genomes__c640bcce
gnomad_allele_frequency__v2_1_1_genomes__774720c3
gnomad_allele_number__v2_1_1_genomes__e944a1c3
gnomad_depth__v2_1_1_genomes__b98619e8
gnomad_homozygotes__v2_1_1_genomes__96b1d837
gnomad_popmax_af__v2_1_1_genomes__c14fd0d2

@AlistairNWard, do we have gnomad v3 fields for variants from a GRCh38 build?

**Comment by AlistairNWard** [comment]
We do:
gnomad_allele_count__v3_1_2_genomes__84b78114
gnomad_allele_frequency__v3_1_2_genomes__bfceffd3
gnomad_allele_number__v3_1_2_genomes__fab93285
gnomad_homozygotes__v3_1_2_genomes__902eb14e
gnomad_popmax_af__v3_1_2_genomes__3e5ec14b
gnomad_variant_depth__v3_1_2_genomes__75d9ee5c

We also have v2 exomes:
gnomad_allele_count__v2_1_1_exomes__91cea8bf
gnomad_allele_frequency__v2_1_1_exomes__32186614
gnomad_allele_number__v2_1_1_exomes__0f20a21f
gnomad_depth__v2_1_1_exomes__756197fd
gnomad_homozygotes__v2_1_1_exomes__60ad3630
gnomad_popmax_af__v2_1_1_exomes__4c2af7e5

**Comment by AlistairNWard** [comment]
All the above are for GRCh38. Also of note - an empty value doesn't mean that there is no value in gnomAD, only that there is no annotation in Mosaic
