### ISSUE TITLE
Add mitochondrial genes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#892]
Ensure that these genes are available

**Comment by tonydisera** [comment]
@YangQi007, would you please run a query on the latest geneinfo gene.iobio.db and let us know which genes are available on chrM? Please report if the are available on RefSeq or GenCode and which genome build. Thanks!

**Comment by YangQi007** [comment]
Please check this csv file about the genes on chrM. [genes_on_chrM.csv](https://github.com/iobio/gene.iobio/files/12821992/genes_on_chrM.csv)

**Comment by tonydisera** [comment]
Thank you for running this query, @YangQi007.

**Comment by tonydisera** [comment]
closed
