### ISSUE TITLE
Add gnomAD homozygous count

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#899]
We currently show the gnomAD AF, but could we also get and display the count of homozygotes?

If we have this, could we also add this to the custom filter page?

**Comment by tonydisera** [comment]
We would need to add this to vcfAnno in annotateVariantsV2.sh.

**Comment by emersonlebleu** [comment]
Clarrification on this homozygote count seems to be showing here in the variant inspect card.

<img width="233" alt="Screenshot 2023-10-05 at 1 03 43 PM" src="https://github.com/iobio/gene.iobio/assets/45885321/84191e37-ce6b-41f2-82a5-c68179d4b3e8">

Is there somewhere else we are wanting this to show? The "custom filter page" is mentioned (I'm not familiar with this component is it called something else?) and Tony mentioned adding this information to "vcfAnno in annotateVariantsV2.sh" which is part of the backend code.

**Comment by AlistairNWard** [comment]
It looks like this must have been added since the issue was created.

For the custom filter, if you are in the variants tab of the left menu, there is a button to Add filter. Click on this and there is a modal to specify filters. It would be good to have the option to filter on homozygotes in this filter.

**Comment by emersonlebleu** [comment]
Got it! thanks Al I see that popup now.
