### ISSUE TITLE
Conflicting ClinVar icons

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#902]
Hey Tony, this is an odd one. There are occasions where the ClinVar icon in the left menu and the variant card are different colours. Any idea why?

This one is red in the menu and gray in the card

![Screenshot 2023-02-13 at 4 08 31 PM](https://user-images.githubusercontent.com/523111/218574892-36d1ba93-a8df-4022-94b9-3c012436441c.png)

In the ClinVar vcf, there are two variants at this location, one is conflicting and one is Pathogenic. Is this causing a conflict? Note that the first entry has no alt.

```
1       169549811       226007  C       .       .       .       ALLELEID=227743;CLNDISDB=MONDO:MONDO:0020586,MedGen:C0015499,OMIM:227400,SNOMED_CT:4320005|MedGen:CN517202;CLNDN=Factor_V_deficiency|not_provided;CLNHGVS=NC_000001.11:g.169549811%3D;CLNREVSTAT=criteria_provided,_conflicting_interpretations;CLNSIG=Conflicting_interpretations_of_pathogenicity;CLNSIGCONF=Pathogenic(1)|Benign(2);CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;CLNVI=PharmGKB_Clinical_Annotation:1183689558;GENEINFO=F5:2153;MC=SO:0002073|no_sequence_alteration;ORIGIN=1
1       169549811       642     C       T       .       .       ALLELEID=15681;CLNDISDB=.|.|Human_Phenotype_Ontology:HP:0002140,MedGen:C0948008,OMIM:601367,SNOMED_CT:422504002|MONDO:MONDO:0008560,MedGen:C1861171,OMIM:188055|MONDO:MONDO:0013727,MedGen:C3280670,OMIM:614389|MONDO:MONDO:0020586,MedGen:C0015499,OMIM:227400,SNOMED_CT:4320005|MeSH:D030342,MedGen:C0950123|MedGen:CN169374;CLNDN=Budd-Chiari_syndrome,_susceptibility_to|Susceptibility_to_severe_coronavirus_disease_(COVID-19)_due_to_an_impaired_coagulation_process|Ischemic_stroke|Thrombophilia_due_to_activated_protein_C_resistance|Pregnancy_loss,_recurrent,_susceptibility_to,_1|Factor_V_deficiency|Inborn_genetic_diseases|not_specified;CLNHGVS=NC_000001.11:g.169549811C>T;CLNREVSTAT=criteria_provided,_multiple_submitters,_no_conflicts;CLNSIG=Pathogenic/Pathogenic,_low_penetrance|risk_factor;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;CLNVI=OMIM_Allelic_Variant:612309.0001|UniProtKB_(protein):P12259#VAR_001213;GENEINFO=F5:2153;MC=SO:0001583|missense_variant;ORIGIN=17;RS=6025
```

Second example. This screenshot has a red icon and a pink icon. In the VCF, this is a Pathogenic/Likely_pathogenic variant

![Screenshot 2023-02-13 at 4 06 09 PM](https://user-images.githubusercontent.com/523111/218574530-b1b17b08-8793-45ce-9bcb-c205e5da87d8.png)

**Comment by AlistairNWard** [comment]
@tonydisera This isn't from a Mosaic project, it's from a Nebula user, so I'm also not able to replicate. The only thing I could do was look at the ClinVar data based on the coordinates in the screenshot and since there are two variants, I was just wondering if this was the issue. I'll try and manufacture a test case

**Comment by AlistairNWard** [comment]
Could this be a Nebula version issue? I created a vcf file that just included the variants in these screenshots, but they don't look the same as the screenshots from the user.
F5 variant: has the same clinVar details, but we have more gnomAD info in prod
ANKS6 variant: can you see an error in the variant I put in? We aren't picking up the same clinvar info or gnomAD info

![Screenshot 2023-03-09 at 10 38 51 AM](https://user-images.githubusercontent.com/523111/224075010-4951629e-4eea-49bd-923b-ed16ab830fa6.png)

![Screenshot 2023-03-09 at 10 44 21 AM](https://user-images.githubusercontent.com/523111/224076617-f9b89abe-33f6-43fb-9a35-8ef0710a492b.png)

**Comment by AlistairNWard** [comment]
Ok, I flipped the alleles around and now I see it. I'll share the vcf on Slack

![Screenshot 2023-03-09 at 10 49 26 AM](https://user-images.githubusercontent.com/523111/224078105-865ff5fa-4149-4faa-9eb4-a46d6c8d7d02.png)

**Comment by tonydisera** [comment]
@AlistairNWard Thanks for providing the file so I could reproduce the bug. The problem was the classification of 'Pathogenic/likely pathogenic'. Now, it will be assigned the level of "likely pathogenic".  Now the code that assigns the clinvar significance level is centralized so that both the filtered variants panel and the variant inspect card will call the same method to assign the level, which determines the color of the clinvar icon.

You noticed that the alleles are reversed. Since this gene is on antisense strand, we show the complement of the alt and ref alleles. But we only do this in 'simplified' mode for Nebula and 'basic' mode for MyGene2. Perhaps this is just too confusing and we should be consistent. What would your vote be?  The HGVS matches what shows in simplified mode. 
<img width="331" alt="Screenshot 2023-03-09 at 8 35 31 PM" src="https://user-images.githubusercontent.com/8420103/224216995-8c14fe14-0321-4144-bf89-60100db500af.png">

**Comment by AlistairNWard** [comment]
Pathogenic/Likely_pathogenic (and Benign/Likely_benign) are valid classifications - they don't need to be set as either Pathogenic or Likely Pathogenic. Can we allow these classifications to be included?

Oh, I see. My opinion (but maybe this is isn't universal) is that the alleles as shown are the ref and alt alleles, not the alleles relative to the gene strand. The alleles need to be consistent with the quoted allele frequencies etc. If I see the alleles as C > T and the allele frequency is 0.1, then it is the minor allele (e.g. T) that is seen in 10% of the population. If we flip the alleles around, are we now suggesting that the minor allele (now the C) is at 90% in the population, and also suggesting that the reference is a C? Unless there is a convention that I'm unaware of, we need to be sure that quoted allele match all other information.
