### ISSUE TITLE
Undefined allele

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#903]
Report from a user where the alt allele is undefined. I'm going to try and replicate

![Screenshot 2023-02-21 at 3 28 06 PM](https://user-images.githubusercontent.com/523111/220451201-99ef58fa-e5ff-4b87-ae55-03b88a3e450f.png)

**Comment by tonydisera** [comment]
@AlistairNWard - You verified that this is working in the latest version of gene.iobio, right? Can I close this issue?

**Comment by AlistairNWard** [comment]
Yep
