### ISSUE TITLE
Use csi as well as tbi indexes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#906]
If the vcf file is indexed with no command line arguments (`bcftools index $VCF`), the default index is a csi, not tbi file. If we launch from Mosaic and the vcf only has csi files, it fails as it's looking for a tbi. We should allow csi files

**Comment by tonydisera** [comment]
Would you mind pointing me to a Mosaic project with a .csi file?  Thanks!

**Comment by tonydisera** [comment]
I see the problem. We are using vcfReadDepther in gene.iobio. This is C++ code that uses the tbi to figure out read depth. We really don't need this functionality in gene.iobio. It is used to get the ref lengths for genome build validation. I will convert this code to just read the vcf header.

**Comment by tonydisera** [comment]
I can replace the vcfReadDepther with code that reads the contig records from the VCF header, but unfortunately, these records are optional. For example, the clinvar vcf does not have contig header records. We will have to discuss options in our next meeting.
