### ISSUE TITLE
CRAM files with dead link to ref

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#946]
CRAM files include the path to the reference file in the @SQ header lines. Samtools uses this file to recreate the sequence. If the file contains a link to a non accessible reference file, samtools will not be able to recreate the sequence and hence gene.iobio will fail to load any of the coverage information or tracks.

We should:
- [ ] Check the header for the reference and see if the link is accessible
- [ ] If not, link to our own reference genome and provide a warning

**Comment by tonydisera** [comment]
I am closing this issue. The error message indicated that the index was not readable. This was the case, because the index file URL on an S3 bucket was not set with public read permissions.
There is also an issue with Call variants having different results that I will open in a separate issue.
