### ISSUE TITLE
Calling variants on same gene duplicates variants

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#952]
Call variants (alignments only, no vcf files) on a gene. Then call again. Notice how the number of variants doubles.
<img width="1311" alt="Screenshot 2023-07-26 at 8 11 25 AM" src="https://github.com/iobio/gene.iobio/assets/8420103/1079e21c-0202-427d-9c16-4fbe07d20fc1">
<img width="1315" alt="Screenshot 2023-07-26 at 8 11 58 AM" src="https://github.com/iobio/gene.iobio/assets/8420103/7a3f6df5-4ef7-48c9-a493-499d24ad6e41">

**Comment by tonydisera** [comment]
This probable explains the issue that a user was having where they saw more variants when they changed the +/- region to a smaller region.

**Comment by AlistairNWard** [comment]
Yeah, this would make sense
