### ISSUE TITLE
Calling variants returns truncated results or no results for genes

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#953]
When I launch gene with the crams only for the demo trio, many of the genes return 0 called variants.

https://gene.iobio.io/?gene=BRCA2&genes=ARHGAP8,BRCA1,PDHA1,PLXNA1,RAI1,SCN8A,SMARCA2,BRCA2&species=Human&build=GRCh38&affectedSibs=&unaffectedSibs=&rel0=proband&sex0=female&vcf0=&tbi0=&bam0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fcram%2F2021_platinum%2FGRCh38_exomes%2FNA12878.cram&bai0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fcram%2F2021_platinum%2FGRCh38_exomes%2FNA12878.cram.crai&sample0=&affectedStatus0=affected&rel1=mother&sex1=female&vcf1=&tbi1=&bam1=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fcram%2F2021_platinum%2FGRCh38_exomes%2FNA12892.cram&bai1=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fcram%2F2021_platinum%2FGRCh38_exomes%2FNA12892.cram.crai&sample1=&affectedStatus1=unaffected&rel2=father&sex2=male&vcf2=&tbi2=&bam2=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fcram%2F2021_platinum%2FGRCh38_exomes%2FNA12891.cram&bai2=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fcram%2F2021_platinum%2FGRCh38_exomes%2FNA12891.cram.crai&sample2=&affectedStatus2=unaffected

**Comment by tonydisera** [comment]
We need to run this script in the backend to see if the results are truncated there as well.

**Comment by tonydisera** [comment]
```
curl 'https://backend.iobio.io/freebayesJointCallV2' \
  -H 'authority: backend.iobio.io' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: text/plain; charset=UTF-8' \
  -H 'origin: https://gene.iobio.io' \
  -H 'referer: https://gene.iobio.io/' \
  -H 'sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  --data-raw '{"_requestId":"dxdw-idtd","_appendErrors":true,"_attemptNum":1,"alignmentSources":[{"bamUrl":"https://iobio.s3.amazonaws.com/samples/cram/2021_platinum/GRCh38_exomes/NA12878.cram","baiUrl":"https://iobio.s3.amazonaws.com/samples/cram/2021_platinum/GRCh38_exomes/NA12878.cram.crai"},{"bamUrl":"https://iobio.s3.amazonaws.com/samples/cram/2021_platinum/GRCh38_exomes/NA12892.cram","baiUrl":"https://iobio.s3.amazonaws.com/samples/cram/2021_platinum/GRCh38_exomes/NA12892.cram.crai"},{"bamUrl":"https://iobio.s3.amazonaws.com/samples/cram/2021_platinum/GRCh38_exomes/NA12891.cram","baiUrl":"https://iobio.s3.amazonaws.com/samples/cram/2021_platinum/GRCh38_exomes/NA12891.cram.crai"}],"refFastaFile":"./data/references/homo_sapiens/hg38/chr13.fa","region":{"refName":"chr13","start":32314086,"end":32401268},"fbArgs":{"useSuggestedVariants":{"value":true,"defaultValue":true},"limitToSuggestedVariants":{"value":false,"defaultValue":false,"argName":"-l","isFlag":true},"minMappingQual":{"value":0,"defaultValue":0,"argName":"--min-mapping-quality"},"minCoverage":{"value":0,"defaultValue":0,"argName":"--min-coverage"},"useDupReads":{"value":false,"defaultValue":false,"argName":"--use-duplicate-reads","isFlag":true}},"refNames":["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr20","chr21","chr22","chrX","chrY"],"genomeBuildName":"GRCh38","vepREVELFile":"./vep-cache/GRCh38_revel_all_chromosomes_for_vep.tsv.gz","vepAF":true,"isRefSeq":false,"clinvarUrl":"https://backend.iobio.io/static/clinvar/GRCh38/clinvar.vcf.gz","sampleNames":["NA12878","NA12892","NA12891"],"decompose":true}' \
  --compressed
```

**Comment by tonydisera** [comment]
Interesting. I was looking into the truncated genotype field when calling variants on the Nebula user cram. It looks like this bug is also caused by the vt normalize mismatch error. When the -n flag is added, the truncation problem goes away and all of the variants are called.
<img width="1530" alt="Screenshot 2023-07-27 at 5 23 20 PM" src="https://github.com/iobio/gene.iobio/assets/8420103/f3f01c3f-de3c-4f39-ab3b-f71d294a2dbd">

**Comment by tonydisera** [comment]
This bug was caused by vt normalize when it encountered a region with lowercase bases. This results in failure and so the script exited at this point in streaming, resulting in a truncated vcf record.

We are fixing this in iobio gru backend (https://github.com/iobio/iobio-gru-backend/issues/110) by changing the freebayesJoinCallV2.sh.

**Comment by anderspitman** [comment]
Fixedin #111
