### ISSUE TITLE
Regenerate genes.json

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio#965]
Fix bug (gene TRA) where the transcript has no features. In this case, the gene should not be included in genes.json.

**Comment by AlistairNWard** [comment]
Should the gene not be included or just don't run annotations? There could still be variants to view that are in ClinVar, for example

**Comment by tonydisera** [comment]
Regenerate genes.json in a condensed format, reducing size from ~8 MB to ~ 4 MB by using abbreviated field name (gn instead of gene_name) and using an array of values to indicate which build (GRCh37, GRCh38) and source (Gencode, Refseq) the gene is valid for.
