### ISSUE TITLE
Called variants gene count

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#990]
Run on demo demo data and call variants on all genes. There are no called variants for RAI1, but the calling did take place. The bar at the top shows that 5 of 6 genes are called which is misleading. 6 of 6 were called, 5 of 6 have variants returned. I imagine a user will think that calling failed on a gene, so I would say we show 6 of 6 if all genes were called on

**Comment by tonydisera** [comment]
This was fixed by  #1007 which addressed a problem in DangerSummary where we were not caching a changed DangerSummary after calling variants.
